/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JCheckBoxMenuItem;
import javax.swing.JDesktopPane;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;

/**
 *
 * @author HP
 */
public class VistaMenu extends javax.swing.JFrame {

    /**
     * Creates new form Persona
     */
    public VistaMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        DskMenu = new javax.swing.JDesktopPane();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuP = new javax.swing.JMenu();
        MIAlumno = new javax.swing.JMenuItem();
        MIProfesor = new javax.swing.JMenuItem();
        MIAdm = new javax.swing.JMenuItem();
        MIDetRealiza = new javax.swing.JMenuItem();
        MIDisciplina = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        MIEnt = new javax.swing.JMenuItem();
        MIOA = new javax.swing.JMenuItem();
        MISede = new javax.swing.JMenuItem();
        MnMenu = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        jMenuItem4.setText("jMenuItem4");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DskMenu.setBackground(new java.awt.Color(255, 255, 255));

        jToolBar1.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/iconos/User.png"))); // NOI18N
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/iconos/Magnifying Glass.png"))); // NOI18N
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton2);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/iconos/Download.png"))); // NOI18N
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton3);
        jToolBar1.add(jSeparator1);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/iconos/Book.png"))); // NOI18N
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton4);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/iconos/UI » Window.png"))); // NOI18N
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton5);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/iconos/Logo(1).png"))); // NOI18N

        DskMenu.setLayer(jToolBar1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DskMenu.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout DskMenuLayout = new javax.swing.GroupLayout(DskMenu);
        DskMenu.setLayout(DskMenuLayout);
        DskMenuLayout.setHorizontalGroup(
            DskMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(DskMenuLayout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DskMenuLayout.setVerticalGroup(
            DskMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DskMenuLayout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        jLabel1.setText("Dolphin Academy System");

        MenuP.setText("Menu");

        MIAlumno.setText("Alumno");
        MenuP.add(MIAlumno);

        MIProfesor.setText("Profesor");
        MenuP.add(MIProfesor);

        MIAdm.setText("Administradores");
        MIAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIAdmActionPerformed(evt);
            }
        });
        MenuP.add(MIAdm);

        MIDetRealiza.setText("Det. Realiza");
        MenuP.add(MIDetRealiza);

        MIDisciplina.setText("Disciplina");
        MenuP.add(MIDisciplina);

        jMenuItem1.setText("Enc.Realiza");
        MenuP.add(jMenuItem1);

        MIEnt.setText("Entrenamiento");
        MenuP.add(MIEnt);

        MIOA.setText("Oferta Academica");
        MenuP.add(MIOA);

        MISede.setText("Sede");
        MenuP.add(MISede);

        jMenuBar1.add(MenuP);

        MnMenu.setText("Edit");
        jMenuBar1.add(MnMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DskMenu)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 605, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(DskMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MIAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIAdmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MIAdmActionPerformed
    
    
    //GETTERS Y SETTERS
    public JMenuItem getMIDetRealiza() {
        return MIDetRealiza;
    }

    public void setMIDetRealiza(JMenuItem MIDetRealiza) {
        this.MIDetRealiza = MIDetRealiza;
    }

    public JMenuItem getMIDisciplina() {
        return MIDisciplina;
    }

    public void setMIDisciplina(JMenuItem MIDisciplina) {
        this.MIDisciplina = MIDisciplina;
    }

    public JMenuItem getMIEnt() {
        return MIEnt;
    }

    public void setMIEnt(JMenuItem MIEnt) {
        this.MIEnt = MIEnt;
    }

    public JMenuItem getMIOA() {
        return MIOA;
    }

    public void setMIOA(JMenuItem MIOA) {
        this.MIOA = MIOA;
    }

    public JMenuItem getMISede() {
        return MISede;
    }

    public void setMISede(JMenuItem MISede) {
        this.MISede = MISede;
    }

    public JDesktopPane getDskMenu() {
        return DskMenu;
    }

    public void setDskMenu(JDesktopPane DskMenu) {
        this.DskMenu = DskMenu;
    }

    public JMenuItem getMIAdm() {
        return MIAdm;
    }

    public void setMIAdm(JMenuItem MIAdm) {
        this.MIAdm = MIAdm;
    }

    public JMenuItem getMIAlumno() {
        return MIAlumno;
    }

    public void setMIAlumno(JMenuItem MIAlumno) {
        this.MIAlumno = MIAlumno;
    }

    public JMenuItem getMIProfesor() {
        return MIProfesor;
    }

    public void setMIProfesor(JMenuItem MIProfesor) {
        this.MIProfesor = MIProfesor;
    }

    public JMenu getMenuP() {
        return MenuP;
    }

    public void setMenuP(JMenu MenuP) {
        this.MenuP = MenuP;
    }

    public JMenu getMnMenu() {
        return MnMenu;
    }

    public void setMnMenu(JMenu MnMenu) {
        this.MnMenu = MnMenu;
    }

    public JCheckBoxMenuItem getjCheckBoxMenuItem1() {
        return jCheckBoxMenuItem1;
    }

    public void setjCheckBoxMenuItem1(JCheckBoxMenuItem jCheckBoxMenuItem1) {
        this.jCheckBoxMenuItem1 = jCheckBoxMenuItem1;
    }

    public JMenu getjMenu1() {
        return jMenu1;
    }

    public void setjMenu1(JMenu jMenu1) {
        this.jMenu1 = jMenu1;
    }

    public JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    public void setjMenuBar1(JMenuBar jMenuBar1) {
        this.jMenuBar1 = jMenuBar1;
    }

    public JMenuItem getjMenuItem4() {
        return jMenuItem4;
    }

    public void setjMenuItem4(JMenuItem jMenuItem4) {
        this.jMenuItem4 = jMenuItem4;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DskMenu;
    private javax.swing.JMenuItem MIAdm;
    private javax.swing.JMenuItem MIAlumno;
    private javax.swing.JMenuItem MIDetRealiza;
    private javax.swing.JMenuItem MIDisciplina;
    private javax.swing.JMenuItem MIEnt;
    private javax.swing.JMenuItem MIOA;
    private javax.swing.JMenuItem MIProfesor;
    private javax.swing.JMenuItem MISede;
    private javax.swing.JMenu MenuP;
    private javax.swing.JMenu MnMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
