/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import com.toedter.calendar.JDateChooser;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author HP
 */
public class VistaAlumno extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaPersona
     */
    
    public VistaAlumno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DgAlumno = new javax.swing.JDialog();
        PNOA1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        TxtCodAlmn = new javax.swing.JTextField();
        TxtCedulaAlmn = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        TxtNombreAlumn = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        TxtApeAlmn = new javax.swing.JTextField();
        BtnCrearAlmn = new javax.swing.JButton();
        BtnGuardarAlmn = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        DCAlumn = new com.toedter.calendar.JDateChooser();
        jLabel19 = new javax.swing.JLabel();
        TxtDireccionAlmn = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        TxtTelfAlmn = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        TxtEmailAlmn = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        TxtCelularAlmn = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        CbxCategoriaAlmn = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cbxdisciplina = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cbxentrenamiento = new javax.swing.JComboBox<>();
        DlgEliminar = new javax.swing.JDialog();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lbtitutolo1 = new javax.swing.JLabel();
        txteliminarnombre = new javax.swing.JTextField();
        btnconfirmareliminar = new javax.swing.JButton();
        btncancelareliminar = new javax.swing.JButton();
        txteliminarid = new javax.swing.JTextField();
        PNOA = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jbregresar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbAlumno = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        TxtBuscarAlmn = new javax.swing.JTextField();
        BtnCrearJFAlmn = new javax.swing.JButton();
        BtnEditarJFAlmn = new javax.swing.JButton();
        BtnListarJFAlmn = new javax.swing.JButton();
        BtnEliminarJFAlmn = new javax.swing.JButton();
        btnimprimiralum = new javax.swing.JButton();

        PNOA1.setBackground(new java.awt.Color(204, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagenes/LogoCab.png"))); // NOI18N

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Alumno");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Codigo:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel15.setText("Nombres:");

        TxtCodAlmn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCodAlmnActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel16.setText("Cedula:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel17.setText("Apellidos:");

        BtnCrearAlmn.setText("Cancelar");
        BtnCrearAlmn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCrearAlmnActionPerformed(evt);
            }
        });

        BtnGuardarAlmn.setText("Guardar");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel18.setText("Fecha de Nacimiento");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel19.setText("Direccion:");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel20.setText("Telefono:");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel21.setText("Correo:");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel22.setText("Celular:");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel23.setText("Categoria:");

        CbxCategoriaAlmn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Categoria 1", "Categoria 2", "Categoria 3" }));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Disciplina:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Entrenamiento:");

        javax.swing.GroupLayout PNOA1Layout = new javax.swing.GroupLayout(PNOA1);
        PNOA1.setLayout(PNOA1Layout);
        PNOA1Layout.setHorizontalGroup(
            PNOA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNOA1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PNOA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PNOA1Layout.createSequentialGroup()
                        .addGroup(PNOA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PNOA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(PNOA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(PNOA1Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PNOA1Layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PNOA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PNOA1Layout.createSequentialGroup()
                                .addGroup(PNOA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(PNOA1Layout.createSequentialGroup()
                                        .addComponent(TxtCodAlmn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PNOA1Layout.createSequentialGroup()
                                        .addGroup(PNOA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(DCAlumn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(TxtNombreAlumn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(PNOA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PNOA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtCedulaAlmn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtApeAlmn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtDireccionAlmn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PNOA1Layout.createSequentialGroup()
                                .addComponent(TxtTelfAlmn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtEmailAlmn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PNOA1Layout.createSequentialGroup()
                                .addGroup(PNOA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtCelularAlmn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxdisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtnGuardarAlmn, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(PNOA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PNOA1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(CbxCategoriaAlmn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PNOA1Layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addGroup(PNOA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(BtnCrearAlmn))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbxentrenamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 52, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PNOA1Layout.setVerticalGroup(
            PNOA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNOA1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PNOA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(TxtCodAlmn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(TxtCedulaAlmn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PNOA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(TxtApeAlmn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(TxtNombreAlumn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PNOA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(DCAlumn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PNOA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(TxtDireccionAlmn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19)))
                .addGap(18, 18, 18)
                .addGroup(PNOA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(TxtTelfAlmn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(TxtEmailAlmn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PNOA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel22)
                    .addGroup(PNOA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TxtCelularAlmn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel23)
                        .addComponent(CbxCategoriaAlmn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PNOA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbxdisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cbxentrenamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(PNOA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCrearAlmn)
                    .addComponent(BtnGuardarAlmn))
                .addContainerGap())
        );

        javax.swing.GroupLayout DgAlumnoLayout = new javax.swing.GroupLayout(DgAlumno.getContentPane());
        DgAlumno.getContentPane().setLayout(DgAlumnoLayout);
        DgAlumnoLayout.setHorizontalGroup(
            DgAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PNOA1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DgAlumnoLayout.setVerticalGroup(
            DgAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PNOA1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel12.setText("ID:");

        jLabel13.setText("Nombre:");

        lbtitutolo1.setText("¿Seguro que desea Eliminar a la persona Seleccionada?");

        txteliminarnombre.setEditable(false);
        txteliminarnombre.setBackground(new java.awt.Color(255, 255, 255));
        txteliminarnombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnconfirmareliminar.setText("ACEPTAR");

        btncancelareliminar.setText("CANCELAR");

        txteliminarid.setEditable(false);
        txteliminarid.setBackground(new java.awt.Color(255, 255, 255));
        txteliminarid.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout DlgEliminarLayout = new javax.swing.GroupLayout(DlgEliminar.getContentPane());
        DlgEliminar.getContentPane().setLayout(DlgEliminarLayout);
        DlgEliminarLayout.setHorizontalGroup(
            DlgEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DlgEliminarLayout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(DlgEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(DlgEliminarLayout.createSequentialGroup()
                        .addComponent(btnconfirmareliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btncancelareliminar))
                    .addComponent(lbtitutolo1)
                    .addGroup(DlgEliminarLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txteliminarnombre))
                    .addGroup(DlgEliminarLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txteliminarid, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(99, 99, 99))
        );
        DlgEliminarLayout.setVerticalGroup(
            DlgEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DlgEliminarLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lbtitutolo1)
                .addGap(18, 18, 18)
                .addGroup(DlgEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txteliminarid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(26, 26, 26)
                .addGroup(DlgEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txteliminarnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(52, 52, 52)
                .addGroup(DlgEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnconfirmareliminar)
                    .addComponent(btncancelareliminar))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        PNOA.setBackground(new java.awt.Color(204, 255, 255));
        PNOA.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagenes/LogoCab.png"))); // NOI18N

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Alumno");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        PNOA.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 920, -1));

        jbregresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagenes/icons8-izquierda-círculo-36.png"))); // NOI18N
        jbregresar.setBorder(null);
        jbregresar.setBorderPainted(false);
        jbregresar.setContentAreaFilled(false);
        jbregresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbregresarActionPerformed(evt);
            }
        });
        PNOA.add(jbregresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 290, -1, -1));

        TbAlumno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Categoria", "Cedula", "Nombres", "Apellido", "Direccion", "Telefono", "Correo", "Fecha Nac", "Celular"
            }
        ));
        jScrollPane1.setViewportView(TbAlumno);

        PNOA.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 910, 104));

        jLabel3.setText("BUSCAR");
        PNOA.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 69, -1, -1));
        PNOA.add(TxtBuscarAlmn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 66, 260, -1));

        BtnCrearJFAlmn.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        BtnCrearJFAlmn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagenes/new-file_40454 (3).png"))); // NOI18N
        BtnCrearJFAlmn.setText("Crear");
        PNOA.add(BtnCrearJFAlmn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, -1, -1));

        BtnEditarJFAlmn.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        BtnEditarJFAlmn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagenes/document-edit_icon-icons.com_52428 (1).png"))); // NOI18N
        BtnEditarJFAlmn.setText("Editar");
        PNOA.add(BtnEditarJFAlmn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, -1, -1));

        BtnListarJFAlmn.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        BtnListarJFAlmn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagenes/list_notes_930.png"))); // NOI18N
        BtnListarJFAlmn.setText("Listar");
        BtnListarJFAlmn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnListarJFAlmnActionPerformed(evt);
            }
        });
        PNOA.add(BtnListarJFAlmn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, -1, -1));

        BtnEliminarJFAlmn.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        BtnEliminarJFAlmn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagenes/delete-file-icon.png"))); // NOI18N
        BtnEliminarJFAlmn.setText("Eliminar");
        BtnEliminarJFAlmn.setMaximumSize(new java.awt.Dimension(59, 23));
        BtnEliminarJFAlmn.setMinimumSize(new java.awt.Dimension(59, 23));
        PNOA.add(BtnEliminarJFAlmn, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 60, -1, -1));

        btnimprimiralum.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnimprimiralum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagenes/printer_print_22133.png"))); // NOI18N
        btnimprimiralum.setText("Imprimir");
        PNOA.add(btnimprimiralum, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 60, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PNOA, javax.swing.GroupLayout.DEFAULT_SIZE, 971, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PNOA, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtCodAlmnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCodAlmnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCodAlmnActionPerformed

    private void BtnCrearAlmnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCrearAlmnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCrearAlmnActionPerformed

    private void jbregresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbregresarActionPerformed

    }//GEN-LAST:event_jbregresarActionPerformed

    private void BtnListarJFAlmnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnListarJFAlmnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnListarJFAlmnActionPerformed

    public JButton getBtncancelareliminar() {
        return btncancelareliminar;
    }

    public void setBtncancelareliminar(JButton btncancelareliminar) {
        this.btncancelareliminar = btncancelareliminar;
    }

    public JButton getBtnconfirmareliminar() {
        return btnconfirmareliminar;
    }

    public void setBtnconfirmareliminar(JButton btnconfirmareliminar) {
        this.btnconfirmareliminar = btnconfirmareliminar;
    }

    public JTextField getTxteliminarid() {
        return txteliminarid;
    }

    public void setTxteliminarid(JTextField txteliminarid) {
        this.txteliminarid = txteliminarid;
    }

    public JTextField getTxteliminarnombre() {
        return txteliminarnombre;
    }

    public void setTxteliminarnombre(JTextField txteliminarnombre) {
        this.txteliminarnombre = txteliminarnombre;
    }

    public JDialog getDlgEliminar() {
        return DlgEliminar;
    }

    public void setDlgEliminar(JDialog DlgEliminar) {
        this.DlgEliminar = DlgEliminar;
    }

    public JDialog getDgAlumno() {
        return DgAlumno;
    }

    public void setDgAlumno(JDialog DgAlumno) {
        this.DgAlumno = DgAlumno;
    }

    public JButton getBtnCrearAlmn() {
        return BtnCrearAlmn;
    }

    public void setBtnCrearAlmn(JButton BtnCrearAlmn) {
        this.BtnCrearAlmn = BtnCrearAlmn;
    }

    public JButton getBtnCrearJFAlmn() {
        return BtnCrearJFAlmn;
    }

    public void setBtnCrearJFAlmn(JButton BtnCrearJFAlmn) {
        this.BtnCrearJFAlmn = BtnCrearJFAlmn;
    }

    public JButton getBtnEditarJFAlmn() {
        return BtnEditarJFAlmn;
    }

    public void setBtnEditarJFAlmn(JButton BtnEditarJFAlmn) {
        this.BtnEditarJFAlmn = BtnEditarJFAlmn;
    }

    public JButton getBtnEliminarJFAlmn() {
        return BtnEliminarJFAlmn;
    }

    public void setBtnEliminarJFAlmn(JButton BtnEliminarJFAlmn) {
        this.BtnEliminarJFAlmn = BtnEliminarJFAlmn;
    }

    public JButton getBtnGuardarAlmn() {
        return BtnGuardarAlmn;
    }

    public void setBtnGuardarAlmn(JButton BtnGuardarAlmn) {
        this.BtnGuardarAlmn = BtnGuardarAlmn;
    }

    public JButton getBtnListarJFAlmn() {
        return BtnListarJFAlmn;
    }

    public void setBtnListarJFAlmn(JButton BtnListarJFAlmn) {
        this.BtnListarJFAlmn = BtnListarJFAlmn;
    }

    public JComboBox<String> getCbxCategoriaAlmn() {
        return CbxCategoriaAlmn;
    }

    public void setCbxCategoriaAlmn(JComboBox<String> CbxCategoriaAlmn) {
        this.CbxCategoriaAlmn = CbxCategoriaAlmn;
    }

    public JDateChooser getDCAlumn() {
        return DCAlumn;
    }

    public void setDCAlumn(JDateChooser DCAlumn) {
        this.DCAlumn = DCAlumn;
    }

    public JTable getTbAlumno() {
        return TbAlumno;
    }

    public void setTbAlumno(JTable TbAlumno) {
        this.TbAlumno = TbAlumno;
    }

    public JTextField getTxtApeAlmn() {
        return TxtApeAlmn;
    }

    public void setTxtApeAlmn(JTextField TxtApeAlmn) {
        this.TxtApeAlmn = TxtApeAlmn;
    }

    public JTextField getTxtBuscarAlmn() {
        return TxtBuscarAlmn;
    }

    public void setTxtBuscarAlmn(JTextField TxtBuscarAlmn) {
        this.TxtBuscarAlmn = TxtBuscarAlmn;
    }

    public JTextField getTxtCedulaAlmn() {
        return TxtCedulaAlmn;
    }

    public void setTxtCedulaAlmn(JTextField TxtCedulaAlmn) {
        this.TxtCedulaAlmn = TxtCedulaAlmn;
    }

    public JTextField getTxtCelularAlmn() {
        return TxtCelularAlmn;
    }

    public void setTxtCelularAlmn(JTextField TxtCelularAlmn) {
        this.TxtCelularAlmn = TxtCelularAlmn;
    }

    public JTextField getTxtCodAlmn() {
        return TxtCodAlmn;
    }

    public void setTxtCodAlmn(JTextField TxtCodAlmn) {
        this.TxtCodAlmn = TxtCodAlmn;
    }

    public JTextField getTxtDireccionAlmn() {
        return TxtDireccionAlmn;
    }

    public void setTxtDireccionAlmn(JTextField TxtDireccionAlmn) {
        this.TxtDireccionAlmn = TxtDireccionAlmn;
    }

    public JTextField getTxtEmailAlmn() {
        return TxtEmailAlmn;
    }

    public void setTxtEmailAlmn(JTextField TxtEmailAlmn) {
        this.TxtEmailAlmn = TxtEmailAlmn;
    }

    public JTextField getTxtNombreAlumn() {
        return TxtNombreAlumn;
    }

    public void setTxtNombreAlumn(JTextField TxtNombreAlumn) {
        this.TxtNombreAlumn = TxtNombreAlumn;
    }

    public JTextField getTxtTelfAlmn() {
        return TxtTelfAlmn;
    }

    public void setTxtTelfAlmn(JTextField TxtTelfAlmn) {
        this.TxtTelfAlmn = TxtTelfAlmn;
    }

    public JDialog getjDialog1() {
        return DgAlumno;
    }

    public void setjDialog1(JDialog jDialog1) {
        this.DgAlumno = jDialog1;
    }

    public JButton getBtnimprimiralum() {
        return btnimprimiralum;
    }

    public void setBtnimprimiralum(JButton btnimprimiralum) {
        this.btnimprimiralum = btnimprimiralum;
    }
    
    public JComboBox<String> getCbxdisciplina() {
        return cbxdisciplina;
    }

    public void setCbxdisciplina(JComboBox<String> cbxdisciplina) {
        this.cbxdisciplina = cbxdisciplina;
    }

    public JComboBox<String> getCbxentrenamiento() {
        return cbxentrenamiento;
    }

    public void setCbxentrenamiento(JComboBox<String> cbxentrenamiento) {
        this.cbxentrenamiento = cbxentrenamiento;
    }

    public JPanel getPNOA() {
        return PNOA;
    }

    public void setPNOA(JPanel PNOA) {
        this.PNOA = PNOA;
    }

    public JPanel getPNOA1() {
        return PNOA1;
    }

    public void setPNOA1(JPanel PNOA1) {
        this.PNOA1 = PNOA1;
    }

    public JButton getJbregresar() {
        return jbregresar;
    }

    public void setJbregresar(JButton jbregresar) {
        this.jbregresar = jbregresar;
    }

    public JLabel getLbtitutolo1() {
        return lbtitutolo1;
    }

    public void setLbtitutolo1(JLabel lbtitutolo1) {
        this.lbtitutolo1 = lbtitutolo1;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCrearAlmn;
    private javax.swing.JButton BtnCrearJFAlmn;
    private javax.swing.JButton BtnEditarJFAlmn;
    private javax.swing.JButton BtnEliminarJFAlmn;
    private javax.swing.JButton BtnGuardarAlmn;
    private javax.swing.JButton BtnListarJFAlmn;
    private javax.swing.JComboBox<String> CbxCategoriaAlmn;
    private com.toedter.calendar.JDateChooser DCAlumn;
    private javax.swing.JDialog DgAlumno;
    private javax.swing.JDialog DlgEliminar;
    private javax.swing.JPanel PNOA;
    private javax.swing.JPanel PNOA1;
    private javax.swing.JTable TbAlumno;
    private javax.swing.JTextField TxtApeAlmn;
    private javax.swing.JTextField TxtBuscarAlmn;
    private javax.swing.JTextField TxtCedulaAlmn;
    private javax.swing.JTextField TxtCelularAlmn;
    private javax.swing.JTextField TxtCodAlmn;
    private javax.swing.JTextField TxtDireccionAlmn;
    private javax.swing.JTextField TxtEmailAlmn;
    private javax.swing.JTextField TxtNombreAlumn;
    private javax.swing.JTextField TxtTelfAlmn;
    private javax.swing.JButton btncancelareliminar;
    private javax.swing.JButton btnconfirmareliminar;
    private javax.swing.JButton btnimprimiralum;
    private javax.swing.JComboBox<String> cbxdisciplina;
    private javax.swing.JComboBox<String> cbxentrenamiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbregresar;
    private javax.swing.JLabel lbtitutolo1;
    private javax.swing.JTextField txteliminarid;
    private javax.swing.JTextField txteliminarnombre;
    // End of variables declaration//GEN-END:variables
}
